// Path to the index file relative to the web root
export const DATA_PATH = './index.json';
export const REMOTE_BASE_URL = 'https://raw.githubusercontent.com/1264600905/Universal-Blueprints-Online-Server/main/';

export const TRANSLATIONS = {
  en: {
    title: "RimWorld Blueprint Library",
    searchPlaceholder: "Name / Author / ID...",
    sort: "Sort",
    category: "Category",
    refresh: "Refresh",
    refreshing: "Refreshing...",
    download: "Download",
    dimensions: "Dimensions",
    downloads: "Downloads",
    likes: "Likes",
    version: "Version",
    uploaded: "Uploaded",
    updated: "Updated",
    reqMods: "Required Mods",
    noMods: "Vanilla / No mods detected",
    copyId: "Copy ID",
    copied: "ID Copied!",
    unknown: "Unknown",
    author: "Author",
    sortNewest: "Newest",
    sortScore: "Recommended",
    sortDownloads: "Most Downloaded",
    sortLikes: "Top Rated",
    error: "Error loading blueprints",
    empty: "No blueprints found matching your criteria.",
    footer: "RimWorld Universal Blueprint Library",
    unofficial: "Unofficial community tool.",
    imageMissing: "Image Missing",
    modsCount: "mods",
    description: "Description"
  },
  cn: {
    title: "RimWorld 蓝图库",
    searchPlaceholder: "名称 / 作者 / ID...",
    sort: "排序",
    category: "分类",
    refresh: "刷新",
    refreshing: "正在刷新...",
    download: "下载",
    dimensions: "尺寸",
    downloads: "下载量",
    likes: "点赞",
    version: "版本",
    uploaded: "上传时间",
    updated: "更新时间",
    reqMods: "所需模组",
    noMods: "原版 / 无模组",
    copyId: "复制 ID",
    copied: "ID 已复制!",
    unknown: "未知",
    author: "作者",
    sortNewest: "最新发布",
    sortScore: "综合推荐",
    sortDownloads: "最多下载",
    sortLikes: "最多好评",
    error: "加载蓝图失败",
    empty: "未找到匹配的蓝图。",
    footer: "RimWorld 蓝图库",
    unofficial: "非官方社区工具。",
    imageMissing: "图片丢失",
    modsCount: "模组",
    description: "描述"
  }
};